# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadoscnpj', '0003_auto_20180320_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnpj',
            name='cnpj',
            field=models.CharField(default='oi', max_length=200),
            preserve_default=False,
        ),
    ]
