# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadoscnpj', '0005_remove_cnpj_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnpj',
            name='name',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
    ]
