# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=0)),
                ('atividade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadesSecundarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=0)),
                ('atividade', models.CharField(max_length=200)),
                ('atividade_1', models.CharField(max_length=200)),
                ('atividade_2', models.CharField(max_length=200)),
                ('atividade_3', models.CharField(max_length=200)),
                ('atividade_4', models.CharField(max_length=200)),
                ('atividade_5', models.CharField(max_length=200)),
                ('atividade_6', models.CharField(max_length=200)),
                ('atividade_7', models.CharField(max_length=200)),
                ('atividade_8', models.CharField(max_length=200)),
                ('atividade_9', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=0)),
                ('telefone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=0)),
                ('cep', models.CharField(max_length=200)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=0)),
                ('cnpj', models.CharField(max_length=200)),
                ('razao_social', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('situacao', models.CharField(max_length=200)),
                ('natureza_juridica', models.CharField(max_length=200)),
                ('capital_social', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=0)),
                ('socio', models.CharField(max_length=200)),
                ('socio_1', models.CharField(max_length=200)),
                ('socio_2', models.CharField(max_length=200)),
                ('socio_3', models.CharField(max_length=200)),
                ('socio_4', models.CharField(max_length=200)),
            ],
        ),
    ]
