# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dadoscnpj', '0002_auto_20180320_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNPJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dado',
        ),
    ]
