# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadoscnpj', '0006_cnpj_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnpj',
            name='name',
        ),
        migrations.AddField(
            model_name='cnpj',
            name='cnpj',
            field=models.CharField(default='cnpj', max_length=200),
        ),
    ]
